version: '3.8'

services: 
  players_postgresql:
    image: postgres:latest
    
  players_api:
    image: ${DOCKER_REGISTRY-}playersapi
    build:
      context: .
      dockerfile: src/Web/FootballPlayers.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: 
      - players_postgresql
  
  players_web:
    image: ${DOCKER_REGISTRY-}playersweb
    build:
      context: .
      dockerfile: src/Web/FootballPlayers.Web/Dockerfile
    depends_on: 
      - players_postgresql
      - players_api